### ISSUE TITLE
SpawnDummyModel does not work in SCPSL 11.0 beta version.

### ISSUE THREAD

**Issue by Pro845627** [joker-119/AdminTools#13]
Throws `ArgumentException` : The object you want to instantiate is null...
It may cause of this line:
``` GameObject gameObject = UnityEngine.Object.Instantiate(NetworkManager.singleton.spawnPrefabs.FirstOrDefault(p => p.gameObject.name == "Player"));```
“Player" is no longer available :(
thx northwood

**Comment by Pro845627** [comment]
I traversed `spawnPrefabs`, there should be no player prefabs in it.

**Comment by joker-119** [comment]
this is the wrong repo to put this on
